// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNvaicNClQYLYmJH8K470pMIYKy0K6NWk',
    appId: '1:491132251675:web:993fb242ac825cec4792be',
    messagingSenderId: '491132251675',
    projectId: 'flutter-study-96fd6',
    authDomain: 'flutter-study-96fd6.firebaseapp.com',
    storageBucket: 'flutter-study-96fd6.appspot.com',
    measurementId: 'G-73N3THQC2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWcNRGEsodwG2LQeXdLjGY2klfjTYgVNU',
    appId: '1:491132251675:android:59584d64f185403e4792be',
    messagingSenderId: '491132251675',
    projectId: 'flutter-study-96fd6',
    storageBucket: 'flutter-study-96fd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-CJKp8E5vNahKQi-S64qiyfI3r6JPFzI',
    appId: '1:491132251675:ios:e06eb4544f75815a4792be',
    messagingSenderId: '491132251675',
    projectId: 'flutter-study-96fd6',
    storageBucket: 'flutter-study-96fd6.appspot.com',
    iosBundleId: 'com.example.studyfluter',
  );
}
